# 🧹 <b>Data Cleaning</b>
1) <b>Duplicates</b>
    - Finding duplicate row(s)
    - Dropping duplicate row(s)
2)  <b>Incorrect dtypes</b>
    - Postal Code is float64 instead of int64
3) <b>Missing values</b>
    - Finding missing values
    - Replacing missing 
4) <b>Outliers</b>
    - Finding outliers
    - Removing outliers
    
This notebook explains key concepts used in the cleaner class<br>
<i>superstore -> utilities</i>

## <b>Duplicates</b>

In [1]:
import pandas as pd
try:
    df = pd.read_excel("../Superstore 2019.xls", index_col="Row ID")
except FileNotFoundError:
    raise FileNotFoundError("Change file name to Superstore 2019.xls")

df[df.duplicated()] # 1 duplicate found

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
3407,US-2016-150119,2016-04-23,2016-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588

In [2]:
df.loc[3406:3408] # Row 3406 & 3407 are the same

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
3406,US-2016-150119,2016-04-23,2016-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588
3407,US-2016-150119,2016-04-23,2016-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588
3408,US-2016-150119,2016-04-23,2016-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,OFF-BI-10000145,Office Supplies,Binders,Zipper Ring Binder Pockets,7.488,8,0.7,-5.2416

In [3]:
df.drop_duplicates(inplace=True) # Removes 3407 and updates df
df.loc[3406:3408] # 3407 is now gone

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
3406,US-2016-150119,2016-04-23,2016-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588
3408,US-2016-150119,2016-04-23,2016-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,OFF-BI-10000145,Office Supplies,Binders,Zipper Ring Binder Pockets,7.488,8,0.7,-5.2416

## <b>Incorrect dtypes</b>

In [4]:
df.info() # Postal Code's Dtype is float64, should be changed to int64 to avoid .0

<class 'pandas.DataFrame'>
Index: 9993 entries, 1 to 9994
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        9993 non-null   str
 1   Order Date      9993 non-null   datetime64[us]
 2   Ship Date       9993 non-null   datetime64[us]
 3   Ship Mode       9993 non-null   str
 4   Customer ID     9993 non-null   str
 5   Customer Name   9993 non-null   str
 6   Segment         9993 non-null   str
 7   Country/Region  9993 non-null   str
 8   City            9993 non-null   str
 9   State           9993 non-null   str
 10  Postal Code     9982 non-null   float64
 11  Region          9993 non-null   str
 12  Product ID      9993 non-null   str
 13  Category        9993 non-null   str
 14  Sub-Category    9993 non-null   str
 15  Product Name    9993 non-null   str
 16  Sales           9993 non-null   float64
 17  Quantity        9993 non-null   int64
 18  Discount        9993 non-null   float64
 19  Profit          9993 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(1), str(13)
memory usage: 1.9 MB

In [5]:
df["Postal Code"] = df["Postal Code"].astype('Int64') # Changes Dtype
df.info() # Successfully changed

<class 'pandas.DataFrame'>
Index: 9993 entries, 1 to 9994
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        9993 non-null   str
 1   Order Date      9993 non-null   datetime64[us]
 2   Ship Date       9993 non-null   datetime64[us]
 3   Ship Mode       9993 non-null   str
 4   Customer ID     9993 non-null   str
 5   Customer Name   9993 non-null   str
 6   Segment         9993 non-null   str
 7   Country/Region  9993 non-null   str
 8   City            9993 non-null   str
 9   State           9993 non-null   str
 10  Postal Code     9982 non-null   Int64
 11  Region          9993 non-null   str
 12  Product ID      9993 non-null   str
 13  Category        9993 non-null   str
 14  Sub-Category    9993 non-null   str
 15  Product Name    9993 non-null   str
 16  Sales           9993 non-null   float64
 17  Quantity        9993 non-null   int64
 18  Discount        9993 non-null   float64
 19  Profit          9993 non-null   float64
dtypes: Int64(1), datetime64[us](2), float64(3), int64(1), str(13)
memory usage: 1.9 MB

## <b>Missing Values</b>

In [6]:
df.info() # Postal Code has 9982 non-null values instead of 9993

<class 'pandas.DataFrame'>
Index: 9993 entries, 1 to 9994
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        9993 non-null   str
 1   Order Date      9993 non-null   datetime64[us]
 2   Ship Date       9993 non-null   datetime64[us]
 3   Ship Mode       9993 non-null   str
 4   Customer ID     9993 non-null   str
 5   Customer Name   9993 non-null   str
 6   Segment         9993 non-null   str
 7   Country/Region  9993 non-null   str
 8   City            9993 non-null   str
 9   State           9993 non-null   str
 10  Postal Code     9982 non-null   Int64
 11  Region          9993 non-null   str
 12  Product ID      9993 non-null   str
 13  Category        9993 non-null   str
 14  Sub-Category    9993 non-null   str
 15  Product Name    9993 non-null   str
 16  Sales           9993 non-null   float64
 17  Quantity        9993 non-null   int64
 18  Discount        9993 non-null   float64
 19  Profit          9993 non-null   float64
dtypes: Int64(1), datetime64[us](2), float64(3), int64(1), str(13)
memory usage: 1.9 MB

In [7]:
null_postal_codes = df["Postal Code"].isna() #filter

""" 
Notice how all null postal codes come from:
City: Burlington
State: Vermont

Since all these records share the same city & state; we can replace all null values to their postal codes (05401)
"""

df[null_postal_codes]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
2235,CA-2019-104066,2019-12-05,2019-12-10,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,<NA>,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03,7,0.0,67.6599
5275,CA-2017-162887,2017-11-07,2017-11-09,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,<NA>,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20,3,0.0,178.8000
8799,US-2018-150140,2018-04-06,2018-04-10,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,<NA>,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75,5,0.0,336.6350
9147,US-2018-165505,2018-01-23,2018-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,<NA>,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98,2,0.0,42.9914
9148,US-2018-165505,2018-01-23,2018-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,<NA>,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04,6,0.0,2.7336
9149,US-2018-165505,2018-01-23,2018-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,<NA>,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29,13,0.0,406.7154
9387,US-2019-127292,2019-01-19,2019-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,<NA>,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92,4,0.0,37.5624
9388,US-2019-127292,2019-01-19,2019-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,<NA>,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28,1,0.0,5.7716
9389,US-2019-127292,2019-01-19,2019-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,<NA>,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94,3,0.0,152.0232
9390,US-2019-127292,2019-01-19,2019-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,<NA>,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04,1,0.0,0.9588
9742,CA-2017-117086,2017-11-08,2017-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,<NA>,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90,5,0.0,1013.1270

In [8]:
df["Postal Code"] = df["Postal Code"].fillna(5401) # Default for null becomes 5401
df.info() # No null values

<class 'pandas.DataFrame'>
Index: 9993 entries, 1 to 9994
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        9993 non-null   str
 1   Order Date      9993 non-null   datetime64[us]
 2   Ship Date       9993 non-null   datetime64[us]
 3   Ship Mode       9993 non-null   str
 4   Customer ID     9993 non-null   str
 5   Customer Name   9993 non-null   str
 6   Segment         9993 non-null   str
 7   Country/Region  9993 non-null   str
 8   City            9993 non-null   str
 9   State           9993 non-null   str
 10  Postal Code     9993 non-null   Int64
 11  Region          9993 non-null   str
 12  Product ID      9993 non-null   str
 13  Category        9993 non-null   str
 14  Sub-Category    9993 non-null   str
 15  Product Name    9993 non-null   str
 16  Sales           9993 non-null   float64
 17  Quantity        9993 non-null   int64
 18  Discount        9993 non-null   float64
 19  Profit          9993 non-null   float64
dtypes: Int64(1), datetime64[us](2), float64(3), int64(1), str(13)
memory usage: 1.9 MB

## <b>Outliers</b><br>
Outlier detection and removal using IQR method<br><br>
<b>Rules:</b><br>
IQR = Q3 - Q1 (75%, 25% shown in .describe())<br>
Lower Limit: (Q3 * 1.5) - IQR<br>
Upper Limit: (Q1 * 1.5) - IQR<br><br>
Anything above/lower these limits is an outlier<br><br>
Source: https://www.youtube.com/watch?v=A3gClkblXK8

In [ ]:
"""
Columns to be checked:

1. Discount: 
    Normal quantile values & pattern

    Notes:
        -0.8 max discount, a little high but fits in the 0-1 discount range.

2. Quantity:
    Normal quantile values & pattern

3. Sales:
    Abnormal quantile values & pattern

    Notes:
        -min of -6599.97 & Q1 of 1.73 (Issue: big jump)
        -Q3 of 29.36 & max of 8399.97 (Issue: big jump)

    Further invistigation -> Apply IQR

4. Profit
    Abnormal quantile values & pattern

    Notes:
        -min of -6599.97 & Q1 of 1.73

    Further invistigation -> Apply IQR
"""

df.describe()

,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9993,9993,9993.0,9993.000000,9993.000000,9993.000000,9993.000000
mean,2018-04-30 11:50:07.745421,2018-05-04 10:49:45.049534,55191.568698,229.852846,3.789753,0.156188,28.660971
min,2016-01-03 00:00:00,2016-01-07 00:00:00,1040.0,0.444000,1.000000,0.000000,-6599.978000
25%,2017-05-23 00:00:00,2017-05-27 00:00:00,23223.0,17.280000,2.000000,0.000000,1.731000
50%,2018-06-26 00:00:00,2018-06-29 00:00:00,56560.0,54.480000,3.000000,0.200000,8.671000
75%,2019-05-14 00:00:00,2019-05-18 00:00:00,90008.0,209.940000,5.000000,0.200000,29.364000
max,2019-12-30 00:00:00,2020-01-05 00:00:00,99301.0,22638.480000,14.000000,0.800000,8399.976000
std,NaN,NaN,32065.086443,623.276074,2.225149,0.206457,234.271476